[package]
name = "mc_server_panel"
version = "0.0.2"
edition = "2024"


[dependencies]
dir = "0.1.2"
open = "5.3.2"
os_info = "3.11.0"
toml = "0.8.23"
serde = { version = "1.0", features = ["derive"] }
